# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yNUfw7t6aiaOEBZrfb4LPZi0gmz0oonp
"""

lis = [1, 2, 3, 4, 5, 6, 7]
arr = [[i]*i for i in lis if i%2==0]
print(arr)
#Задача 1

x = int(input())
y = int(input())
if(-1 <= x <= 1) and (-1 <= y <= 1):
  print('Принадлежит')
else:
  print('Не принадлежит')
  #Задача 2

A = [1, 2, 4, 5, 6, 7, 7]
B = []
for i in range(6):
  if(A[i]%2 == 0):
    B.append(A[i])
print(B)
#Задача 3

name = input()
print(f'Привет, {name}!')
#Задача 4

chislo = int(input())
print(f'The next number for the number {chislo} is {chislo+1}. The previous number for the number {chislo} is {chislo-1}.')
#Задача 5