# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HLPWgoZyg_AwlOnYwK_Joo79gbL4nRKQ
"""

# Задание 1
a = [1, 2, 3, 4, 5, 6, 7]
for i in a:
  if i % 2 == 0:
    print([a[i-1]] * i)

# Задание 2
x = int(input())
y = int(input())
if x >= -1 and x <= 1 and y >= -1 and y <= 1:
  print("Yes")
else:
  print("No")

# Задание 3
b = []
a = list(input())
a = map(int, a)
for i in a:
    if i % 2 == 0:
      b = b + [i]
print(b)

# Задание 4
name = input()
print(f'Привет, {name}!')

# Задание 5
a = int(input())
b = f'The next number for the number {a} is {a+1}. The previous number for the number {a} is {a-1}.'
print(b)